# Generated by Django 5.2.7 on 2025-10-31 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_country_remove_post_category_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='flag_image',
        ),
    ]
